### After scraping the data of eight cars(8), I cleaned them one by one. In feature engineering notebook 3rd phase, i merged all the cleaned documents of cars into one file.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [339]:
df = pd.read_csv('swift.csv')

In [340]:
df.head()

,name,price,city,year,mileage,feul,engine,driving
0,Suzuki Swift 2010 DLX 1.3 for Sale,PKR 13 lacs,Islamabad,[<li>2010</li>],"[<li>120,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]
1,Suzuki Swift 2010 DLX 1.3 for Sale,PKR 13 lacs,Islamabad,[<li>2010</li>],"[<li>120,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]
2,Suzuki Swift 2020 DLX Automatic 1.3 Navigatio...,PKR 22.25 lacs,Karachi,[<li>2020</li>],"[<li>22,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Automatic</li>]
3,Suzuki Swift 2010 DLX 1.3 for Sale,PKR 13 lacs,Islamabad,[<li>2010</li>],"[<li>120,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]
4,Suzuki Swift 2020 DLX Automatic 1.3 Navigatio...,PKR 22.25 lacs,Karachi,[<li>2020</li>],"[<li>22,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Automatic</li>]

In [341]:
df.shape

(14288, 8)

In [342]:
df.drop_duplicates(inplace=True)

In [343]:
df.shape

(986, 8)

In [344]:
#df2 = df.copy()
#df3 = df.copy()
df4 = df.copy()

In [345]:
df4.shape

(986, 8)

In [140]:
#df2.reset_index()

In [346]:
df4.reset_index(inplace=True)

In [347]:
df4.drop('index',axis=1,inplace=True)

In [348]:
df4.head()

,name,price,city,year,mileage,feul,engine,driving
0,Suzuki Swift 2010 DLX 1.3 for Sale,PKR 13 lacs,Islamabad,[<li>2010</li>],"[<li>120,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]
1,Suzuki Swift 2020 DLX Automatic 1.3 Navigatio...,PKR 22.25 lacs,Karachi,[<li>2020</li>],"[<li>22,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Automatic</li>]
2,Suzuki Swift 2018 DLX 1.3 for Sale,PKR 17.85 lacs,Rawalpindi,[<li>2018</li>],"[<li>55,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]
3,Suzuki Swift 2014 DLX Automatic 1.3 Navigatio...,PKR 16.95 lacs,Lahore,[<li>2014</li>],"[<li>112,000 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Automatic</li>]
4,Suzuki Swift 2018 DLX 1.3 Navigation for Sale,PKR 18.3 lacs,Rawalpindi,[<li>2018</li>],"[<li>69,950 km</li>]",[<li>Petrol</li>],[<li>1300 cc</li>],[<li>Manual</li>]

## Cleaning the features

In [358]:
for r in (("cc", ""), ("<li>", ""),("</li>",""),("\n",""),("   ",""),("[",""),("]","")):
    df4['driving'] = df4['driving'].str.replace(*r,regex=True)

In [359]:
parts = df4['price'].str.split('\.')
part0 = parts.str[0].str.extract('(\d+)').fillna('0')
part1 = parts.str[1].str.extract('(\d+)').fillna('0')
df4['price'] = part0 + "." + part1

In [360]:
df4['mileage']= df4['mileage'].str.replace(r'\D', '')

In [361]:
df4

,name,price,city,year,mileage,feul,engine,driving
0,Suzuki Swift 2010 DLX 1.3 for Sale,13.0,Islamabad,2010,120000,Petrol,1300,Manual
1,Suzuki Swift 2020 DLX Automatic 1.3 Navigatio...,22.25,Karachi,2020,22000,Petrol,1300,Automatic
2,Suzuki Swift 2018 DLX 1.3 for Sale,17.85,Rawalpindi,2018,55000,Petrol,1300,Manual
3,Suzuki Swift 2014 DLX Automatic 1.3 Navigatio...,16.95,Lahore,2014,112000,Petrol,1300,Automatic
4,Suzuki Swift 2018 DLX 1.3 Navigation for Sale,18.3,Rawalpindi,2018,69950,Petrol,1300,Manual
...,...,...,...,...,...,...,...,...
981,Suzuki Swift 2018 DLX 1.3 Navigation for Sale,18.1,Islamabad,2018,75000,Petrol,1300,Manual
982,Suzuki Swift 2013 DLX 1.3 for Sale,13.5,Chakwal,2013,67000,Petrol,1300,Manual
983,Suzuki Swift 2018 DLX 1.3 Navigation for Sale,19.0,Sahiwal,2018,35600,Petrol,1300,Manual
984,Suzuki Swift 2013 DLX 1.3 for Sale,14.35,More kunda,2013,105378,Petrol,1300,Manual
985,Suzuki Swift 2013 DX 1.3 for Sale,12.95,Karachi,2013,50000,Petrol,1300,Manual

In [362]:
df4['name'].unique()

array(['Suzuki Swift  2010 DLX 1.3 for Sale',
       'Suzuki Swift  2020 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2018 DLX 1.3 for Sale',
       'Suzuki Swift  2014 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2018 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2014 DLX 1.3 for Sale',
       'Suzuki Swift  2011 DLX 1.3 for Sale',
       'Suzuki Swift  2017 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2016 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2015 DLX 1.3 for Sale',
       'Suzuki Swift  2021 XG 1.2 for Sale',
       'Suzuki Swift  2021 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2019 DLX 1.3 for Sale',
       'Suzuki Swift  2015 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2017 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2013 DLX 1.3 for Sale',
       'Suzuki Swift  2011 DX 1.3 for Sale',
       'Suzuki Swift  2011 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2014 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2014 DX 1.3 for Sale',
       'Suzuki Swift  2017 RS 1.0 for Sale',
       'Suzuki Swift  2012 DLX 1.3 for Sale',
       'Suzuki Swift  2013 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2021 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2013 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2020 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2017  for Sale',
       'Suzuki Swift  2012 DX 1.3 for Sale',
       'Suzuki Swift  2021 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2015 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2020 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2016 DLX 1.3 for Sale',
       'Suzuki Swift  2013 DX 1.3 for Sale',
       'Suzuki Swift  2017 DLX 1.3 for Sale',
       'Suzuki Swift  2013 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  1990  for Sale',
       'Suzuki Swift  2019 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2006 Sport F Limited 1.6 for Sale',
       'Suzuki Swift  2018  for Sale',
       'Suzuki Swift  2012 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2018 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2016 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2012  for Sale',
       'Suzuki Swift  2019 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2018 RS 1.0 for Sale',
       'Suzuki Swift  2014 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2010 XG 1.3 for Sale',
       'Suzuki Swift  2013  for Sale',
       'Suzuki Swift  2012 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2010 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2017 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2015 DX 1.3 for Sale',
       'Suzuki Swift  2015 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2017 XG 1.2 for Sale',
       'Suzuki Swift  2008  for Sale',
       'Suzuki Swift  2021 XL 1.2 for Sale',
       'Suzuki Swift  1986  for Sale',
       'Suzuki Swift  2008 XG 1.3 for Sale',
       'Suzuki Swift  2009 XG 1.3 for Sale',
       'Suzuki Swift  2009 DX 1.3 for Sale',
       'Suzuki Swift  2016 DLX 1.3 Navigation  for Sale',
       'Suzuki Swift  2005 XG L Package 1.3 for Sale',
       'Suzuki Swift  2014  for Sale',
       'Suzuki Swift  2021 DLX 1.3 for Sale',
       'Suzuki Swift  2005 Sport 1.6 for Sale',
       'Suzuki Swift  1986 RS 1.0 for Sale',
       'Suzuki Swift  2007 XG 1.2 for Sale',
       'Suzuki Swift  1989  for Sale',
       'Suzuki Swift  2006 XG 1.3 for Sale',
       'Suzuki Swift  2016  for Sale', 'Suzuki Swift  2010  for Sale',
       'Suzuki Swift  2008 XG 1.2 for Sale',
       'Suzuki Swift  2020 DLX 1.3 for Sale',
       'Suzuki Swift  2020 RS 1.0 for Sale',
       'Suzuki Swift  2017 XL 1.2 for Sale',
       'Suzuki Swift  2011 XG 1.2 for Sale',
       'Suzuki Swift  2011  for Sale',
       'Suzuki Swift  2019 DLX Automatic 1.3 for Sale',
       'Suzuki Swift  2017 DX 1.3 for Sale',
       'Suzuki Swift  2006  for Sale', 'Suzuki Swift  2021  for Sale',
       'Suzuki Swift  2010 XG L Package 1.3 for Sale',
       'Suzuki Swift  2007 XG 1.3 for Sale',
       'Suzuki Swift  2004 XG 1.3 for Sale',
       'Suzuki Swift  2018 DX 1.3 for Sale',
       'Suzuki Swift  1987  for Sale',
       'Suzuki Swift  2012 RS 1.2 for Sale',
       'Suzuki Swift  2011 XS 1.2 for Sale',
       'Suzuki Swift  2014 XL 1.2 for Sale',
       'Suzuki Swift  2011 DLX Automatic 1.3 Navigatio...',
       'Suzuki Swift  2015 RS 1.0 for Sale',
       'Suzuki Swift  2005  for Sale',
       'Suzuki Swift  2016 DX 1.3 for Sale',
       'Suzuki Swift  2015  for Sale',
       'Suzuki Swift  2010 DX 1.3 for Sale',
       'Suzuki Swift  2005 Sport F Limited 1.6 for Sale',
       'Suzuki Swift  2006 XG L Package 1.3 for Sale',
       'Suzuki Swift  2010 Sport 1.6 for Sale',
       'Suzuki Swift  1985 RS 1.0 for Sale',
       'Suzuki Swift  2019 XL 1.2 for Sale',
       'Suzuki Swift  1998  for Sale', 'Suzuki Swift  1991  for Sale',
       'Suzuki Swift  2008 Sport 1.6 for Sale',
       'Suzuki Swift  1994  for Sale'], dtype=object)

In [363]:
df4['name'].str.split(' ').str.slice(0,5,4).str.join(' ')

0      Suzuki DLX
1      Suzuki DLX
2      Suzuki DLX
3      Suzuki DLX
4      Suzuki DLX
          ...
981    Suzuki DLX
982    Suzuki DLX
983    Suzuki DLX
984    Suzuki DLX
985     Suzuki DX
Name: name, Length: 986, dtype: object

In [169]:
#df4['model_name'] = 'Suzuki VX'

In [364]:
df4['model_name'] = df4['name'].str.split(' ').str.slice(0,5,4).str.join(' ')

In [365]:
df4['name'] = 'suzuki swift'

In [183]:
#df4.loc[df4['year'] < '2001', df4['model_name']] = 'Suzuki GL'
#df4.loc[(df4.year < '2001'), df4.model_name]='Suzuki GL'
df4.loc[df4.year < '2001', 'model_name'] = "Suzuki GL"

In [226]:
df4[df4['year']<'1995']

,name,price,city,year,mileage,feul,engine,driving,model_name
51,honda civic,6.0,Peshawar,1985,140000,Petrol,1200,Manual,Honda GL
53,honda civic,7.75,Multan,1994,48000,Petrol,1500,Manual,Honda EX
142,honda civic,6.35,Lahore,1994,150000,Petrol,1600,Automatic,Honda
236,honda civic,14.0,Islamabad,1994,62000,Petrol,1500,Automatic,Honda
258,honda civic,9.6,Islamabad,1981,77389,Petrol,1300,Manual,Honda
...,...,...,...,...,...,...,...,...,...
6949,honda civic,3.4,Islamabad,1985,110000,Petrol,1600,Manual,Honda VTi
6962,honda civic,5.3,Hyderabad,1994,180000,Petrol,1500,Manual,Honda EX
6963,honda civic,2.8,Multan,1985,150000,CNG,1300,Manual,Honda EXi
6969,honda civic,5.3,Hyderabad,1994,180000,Petrol,1500,Manual,Honda
7027,honda civic,5.7,Lahore,1988,106000,Petrol,1600,Automatic,Honda EXi

In [366]:
df4.to_csv('cleaned_suzuki_swift.csv',index=False)

In [314]:
df = pd.read_csv('cleaned_kia_sportage.csv')

In [315]:
df

,name,price,city,year,mileage,feul,engine,driving,model_name
0,Kia Sportage,55.15,Sialkot,2020,4300,Petrol,2000,Automatic,KIA AWD
1,Kia Sportage,52.95,Islamabad,2020,11384,Petrol,2000,Automatic,KIA FWD
2,Kia Sportage,0.00,Lahore,2021,2400,Petrol,2000,Automatic,KIA AWD
3,Kia Sportage,57.40,Islamabad,2021,3000,Petrol,2000,Automatic,KIA AWD
4,Kia Sportage,57.50,Islamabad,2021,25,Petrol,2000,Automatic,KIA AWD
...,...,...,...,...,...,...,...,...,...
883,Kia Sportage,57.10,Lahore,2021,1,Petrol,2000,Automatic,KIA AWD
884,Kia Sportage,57.50,Lahore,2021,100,Petrol,2000,Automatic,KIA AWD
885,Kia Sportage,57.25,Islamabad,2021,25,Petrol,2000,Automatic,KIA AWD
886,Kia Sportage,55.30,Islamabad,2020,28,Petrol,2000,Automatic,KIA AWD
887,Kia Sportage,59.00,Lahore,2020,180,Petrol,2000,Automatic,KIA AWD